= Softwareentwicklung im Team: Klausurzulassung (Team: Bits_please)
WS19/20
:icons: font
:icon-set: octicon
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

=== Management Summary

==== Problemstatement

* Aktuell werden die Klausurzulassungen in den jeweiligen Fachbereichen vollständig manuell verwaltet.
* Dies ist ineffizient und es besteht die Gefahr, dass Nachweise von Altzulassungen von Studenten verloren gehen.

==== Wesentliche Ziele und Features

* Wesentliche Ziele:
** Es soll ein System geschrieben werden, bei dem die Studenten eine kryptographisch signierte Datei als Nachweis der bestandenen Klausurzulassung per Email erhalten.
** Dieser Nachweis soll durch das System aus Kulanzgründen für eine begrenzte Zeit (z.B. ein Jahr) gespeichert werden. Danach wird die Datei endgültig gelöscht.
** Somit kann die Verantwortung für die Aufbewahrung der Nachweise auf den Studenten übertragen werden. Außerdem vermeiden die Fachbereiche eventuelle Probleme mit der Datenschutzverordnungen.

* Features:
** Die Organisatoren sollen in einer Maske eine Datei (im .csv-Format) mit Namen und Emailadressen von Studenten hochladen können. Der Name der Veranstaltung soll manuell eingetippt werden.
** Das System soll signierte Dateien im .txt-Format als Nachweis für diese Veranstaltung erstellen. Dabei soll eine etablierte Library zur Verschlüsselung genutzt werden (Asymmetrische Verschlüsselung)
** Ein Button soll dann Emails mit den Nachweisen im Anhang an die Studenten versenden.
** Die Organisatoren sollen einen Nachweis in einer Maske hochladen können.
** Eine Nachricht auf dem Bildschirm soll dem Organisator mitteilen ob der Nachweis echt ist.
** Die Organisatoren sollen eine Liste von angemeldeten Studenten (aus einem anderen System z.B. Studierendenportal) hochladen können.
** Das System soll selbstständig suchen ob ein Nachweis gespeichert ist und den Status des Studenten auf "zugelassen" ändern.
** Falls nicht sollen die Studierenden per Email darüber informiert werden, dass sie einen Nachweis erbringen müssen.
** Die Studierenden sollen dann selbst den Nachweis in der o.g. Maske hochladen. Der Status des Studenten soll dann auf "zugelassen" geändert werden.

==== Dokumentation

Eine Dokumentation im arc42-Format ist im Repository unter /dokumentation zu finden.