[[section-introduction-and-goals]]
==	Einführung und Ziele

[role="arc42help"]

=== Zugrundeliegenden Geschäftsziele:
 - Aktuell werden die Klausurzulassungen in den jeweiligen Fachbereichen vollständig manuell verwaltet.
 - Dies soll durch ein System ersetzt werden bei dem die Studenten eine kryptographisch signierte Datei als Nachweis der bestandenen Klausurzulassung per Email erhalten.
 - Dieser Nachweis soll durch das System aus Kulanzgründen für eine begrenzte Zeit gespeichert werden. Danach wird die Datei endgültig gelöscht.


=== Aufgabenstellung und fachliche Anforderungen

[role="arc42help"]
 - Wir sollen asymmetrische Verschüsselung benutzen.
 - Das System generiert eine Datei als plain text (txt).
 - Der Inhalt der Datei wird gehasht.
 - Der Hash wird in die Datei geschrieben.
 - Der gehashte Wert wird mit private key verschlüsselt --> wird verschickt
  - Student erhlät text und gehashten WErt --> public key kann
 - UNser System hat einen private - public key Schlüsselpärchen.
 - Die Signatur wird mit dem private key erstellt und mit dem public key kann dies verifiziert werden.
 - Der Input erfolgt als csv-Datei die die Namen der Studenten und den Status der Zulassung enthält.
 - Wir benötigen ein Interface zum Einlesen der csv-Datei.
 - Wir brauchen eine Schnittstelle zu einem Email-Client. Die Email soll als plain text verschickt werden. Die verschlüsselte Datei soll im txt-Format sein.

=== Qualitätsziele

[role="arc42help"]

[cols="1,1" options="header"]
|===
|Qualitätsziel | Motivation und Erläuterung
| Innerhalb kurzer Zeit (4 Wochen) eine stabile, funktionierende Webanwendung zu realisieren. | Da alle im Programmierteam realtiv unerfahrene Programmierer sind und wir nur einen sehr begrenzten Zeitraum zur realisierung haben ist effektives Zeit- und Ressourcenmanagement eine wesentlicher Erfolgsfaktor
| Sichere, stabile kryptographische Verschlüsselung der Datei. | Selbsterklärend.
| Exzellente User Experience | Eine angenehme user exeprience ist ...
|===

* hallo

=== Stakeholder

[role="arc42help"]
.Inhalt
Expliziter Überblick über die Stakeholder des Systems – über alle Personen, Rollen oder Organisationen –, die

* die Architektur kennen sollten oder
* von der Architektur überzeugt werden müssen,
* mit der Architektur oder dem Code arbeiten (z.B. Schnittstellen nutzen),
* die Dokumentation der Architektur für ihre eigene Arbeit benötigen,
* Entscheidungen über das System und dessen Entwicklung treffen.

.Motivation
Sie sollten die Projektbeteiligten und -betroffenen kennen, sonst erleben Sie später im Entwicklungsprozess Überraschungen.
Diese Stakeholder bestimmen unter anderem Umfang und Detaillierungsgrad der von Ihnen zu leistenden Arbeit und Ergebnisse.

.Form
Tabelle mit Rollen- oder Personennamen, sowie deren Erwartungshaltung bezüglich der Architektur und deren Dokumentation.

[cols="1,1" options="header"]
|===
|Rolle | Interesse, Bezug
| Entwicklungsteam | ....
| Lehrstuhl für Softwaretechnik | ...
| Die Entwicklungsteam der anderen Teilsysteme | ...
|===
