[[section-building-block-view]]
== Building Block View

[role="arc42help"]
****

[cols="1,1" options="header"]

==== Ebene 1: Datenbankzugriff
|===
| Subsystem | Kurzbeschreibung
| Studentrepo | Speichert Studenten in der Datenbank
| Modulrepo | Speichert Module in der Datenbank
| Quittungenrepo | Speichert Quittungen in der Datenbank
| Statistikrepo | Speichert Statistik in der Datenbank
|===

==== Ebene 2: Logik
|===
| Subsystem | Kurzbeschreibung
| CsvService | Liest csv Dateien ein und erstellt Studenten und schreibt die Zulassungsliste
| EmailService | Verschickt E-Mails mit Tokens an neu zugelassene Studenten
| ModulService | Findet und speichert Module
| QuittungService | Speichert Quittungen und kann über die Quittung den publickey finden
| StudentenService | Findet und speichert Studenten
| TokengenerierungsService | Erstellt anhand der Matrikelnummer und der FachID und einem Keypair ein Token
| TokenverifikationsService | Entschlüsselt anhand der Matrikelnummer und der FachID den Token zur Verifikation
| StatistikService | Findet Statistik Modul
|===

==== Ebene 3: Grafische Oberfläche
|===
| Subsystem | Kurzbeschreibung
| MainController | Stellt die Links zu weiteren Navigation auf der Seite und liefert eine Beschreibung der Rollen
| ModulController | Erstellt Module, lädt Zulassungslisten hoch und kombiniert diese mit der Altzulassungsliste
| StudentenController | Lädt Altzulassungen hoch mit allen nötigen Daten
| StatistikController | Selektiert eine Statistik
|===

=== Aufgabe 5.2 Tokensystem
==== Zweck/Verantwortlichkeit
Dieses Subsystem ist zuständig für die Tokengenerierung- und verifikation. Das Subsystem bekommt vom Organisatorensystem
die Strings MatrNr und FachID übergeben, generiert einen Token und gibt einen String zurück. In der Tokenverifikation
werden drei Strings übergeben die MatrNr, die FachID und der Token, womit das Token verifiziert werden kann.


=== Aufgabe 5.3 Organisatoren

Organisatoren haben die Möglichkeit ein Modul zu erstellen welches die Veranstaltung bzw. das Fach repräsentiert.
Das Modul hat eine eigene Fachid damit jedem Modul mehrere Studenten zugeordnet werden können.
Der Organisator kann eine Zulassungsliste (csv-file) in der Applikation hochladen. Diese wird eingelesen und aus
dieser Liste werden Studenten Objekte erstellt. Jedem zugelassenem Studenten wird eine E-Mail geschickt.
Diese Studenten werden dann abgeglichen mit den Studenten die schon eine Altzulassung haben und daraus wird eine Klausurzulassungsliste erstellt.
Des weiteren besteht die Möglichkeit als Organisator, falls die Zulassungen von Studenten erreicht worden sind, für
jeden einzelnen Studenten ein Token generieren zu lassen und es per Email weiterzuleiten.

=== Aufgabe 5.4 Studenten

Der Student hat die Möglichkeit mithilfe des Tokens welches er per E-Mail geschickt bekommen hat sich für die Klausur
im nächsten Jahr wieder zuzulassen.
In der E-Mail, welche er bekommt, kann er auf einen Link klicken und wird automatisch auf ein Formular weitergeleitet
welches, schon mit dem Token ausgefüllt wurde.
Hier muss er noch ggf. ein paar Informationen eingeben und kann sich ganz einfach als zugelassen verifizieren.

=== Aufgabe 5.5 E-Mail-Service

Der E-Mail-Service ist dazu da um Emails an die verschiedenen Studenten zu schicken, welche eine Zulassung erhalten
haben.
Die E-Mail beinhaltet den Token sowie einen Link zum automatischen Ausfüllen der Daten auf der Studentenseite.
