[[section-runtime-view]]
== Laufzeitsicht

[role="arc42help"]
****
.Inhalt
Diese Sicht erklärt konkrete Abläufe und Beziehungen zwischen Bausteinen in Form von Szenarien aus den folgenden Bereichen:

*  Wichtige Abläufe oder _Features_:
Wie führen die Bausteine der Architektur die wichtigsten Abläufe durch?
*  Interaktionen an kritischen externen Schnittstellen:
Wie arbeiten Bausteine mit Nutzern und Nachbarsystemen zusammen?
* Betrieb und Administration: Inbetriebnahme, Start, Stop.
* Fehler- und Ausnahmeszenarien

Anmerkung:
Das Kriterium für die Auswahl der möglichen Szenarien (d.h. Abläufe) des Systems ist deren Architekturrelevanz.
Es geht nicht darum, möglichst viele Abläufe darzustellen, sondern eine angemessene Auswahl zu dokumentieren.

.Motivation
Sie sollten verstehen, wie (Instanzen von) Bausteine(n) Ihres Systems ihre jeweiligen Aufgaben erfüllen und zur Laufzeit miteinander kommunizieren.

Nutzen Sie diese Szenarien in der Dokumentation hauptsächlich für eine verständlichere Kommunikation mit denjenigen Stakeholdern, die die statischen Modelle (z.B. Bausteinsicht, Verteilungssicht) weniger verständlich finden.

.Form
Für die Beschreibung von Szenarien gibt es zahlreiche Ausdrucksmöglichkeiten.
Nutzen Sie beispielsweise:

* Nummerierte Schrittfolgen oder Aufzählungen in Umgangssprache
* Aktivitäts- oder Flussdiagramme
* Sequenzdiagramme
* BPMN (Geschäftsprozessmodell und -notation) oder EPKs (Ereignis-Prozessketten)
* Zustandsautomaten
* ...
****

=== _<Bezeichnung Laufzeitszenario 1>_
.Anmeldeliste hochladen:
* Der Organisator kann hier eine CSV Datei hochladen die eine Liste mit allen Studenten enthält die in einem Modul zur Prüfung angemeldet sind und das Fach sowie die Abgabefrist für das Nachreichen einer Klausurzulassung bestimmen.
* Nach dem Hochladen wird überprüft welche Studenten aus der Datei eine gültige Zulassung besitzen.
* Die Studenten werden dann nach zugelassen und nicht zugelassen aufgeteilt.
* Weiterhin kann eine Warnungsnachricht an individuelle Studenten oder an alle gesendet werden, sollten diese keine gültige Zulassung haben.

*  <hier Laufzeitdiagramm oder Ablaufbeschreibung einfügen>
*  <hier Besonderheiten bei dem Zusammenspiel der Bausteine in diesem Szenario erläutern>

=== _<Bezeichnung Laufzeitszenario 2>_
.Zulassungsliste hochladen:
* Der Organisator kann hier eine CSV Datei, die alle Studenten die zu einer Klausur zugelassen sind enthält hochladen und das Fach sowie das Semester bestimmen.
Nach dem Hochladen werden alle Studenten der Datei aufgelistet angezeigt.
* Nun kann den Studenten jeweils einzeln oder an alle Studenten gleichzeitig eine Email gesendet werden, welche als Bestätigung für die Zulassung dient.

=== _<Bezeichnung Laufzeitszenario n>_
.Quittungen validieren:
* Hier kann vom Organisator oder Studenten eine Quittung hochgeladen werden. Diese Quittung wird vom System überprüft und es wird eine aussagekräftige Nachricht zurückgegeben
je nachdem ob die Quittung gültig ist oder nicht. Eine gültige Quittung bedeutet, dass der Student zu dem diese gehört zugelassen ist.

