[[section-design-decisions]]
== Entwurfsentscheidungen

[role="arc42help"]
****
.Inhalt
Wichtige, teure, große oder riskante Architektur- oder Entwurfsentscheidungen inklusive der jeweiligen Begründungen.
Mit "Entscheidungen" meinen wir hier die Auswahl einer von mehreren Alternativen unter vorgegebenen Kriterien.

Wägen Sie ab, inwiefern Sie Entscheidungen hier zentral beschreiben, oder wo eine lokale Beschreibung (z.B. in der Whitebox-Sicht von Bausteinen) sinnvoller ist.
Vermeiden Sie Redundanz.
Verweisen Sie evtl. auf Abschnitt 4, wo schon grundlegende strategische Entscheidungen beschrieben wurden.

.Motivation
Stakeholder des Systems sollten wichtige Entscheidungen verstehen und nachvollziehen können.

.Form
Verschiedene Möglichkeiten:

* Liste oder Tabelle, nach Wichtigkeit und Tragweite der Entscheidungen geordnet
* ausführlicher in Form einzelner Unterkapitel je Entscheidung
* ADR (http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Architecture Decision Record]) für jede wichtige Entscheidung
****

****
.Verschlüsselung:
* Das Zulassungstoken, dass die Studenten erhalten muss mit einer Verschlüsselungsmethode verschlüsselt werden. Dafür entschieden wir uns für die Hashfunktion
sha256 mit RSA, da diese als praktisch nicht entschlüsselbar gilt.

.Speicherung der Quittungen:
* Die Quittungen werden aus Datenschutzrechtlichen Gründen lediglich für einen begrenzten Zeitraum, aktuell von 3 Jahren abgespeichert.
Innerhalb dieses Zeitraums können die Quittungen vom Server heruntergeladen werden. Für die Speicherung haben wir uns für MinIO entschieden.

.Datenbank:
* Wir haben uns absichtlich gegen eine Datenbank entschieden, da dies aus Datenschutzrechtlichen Gründen eventuell schwierig durchzusetzen ist.
****